name: CI Pipeline

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  pull_request:
    branches:
      - main  # Runs on PRs targeting main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install pylint black pytest

#      - name: Run Unit Tests
#        run: bazel test //tests:test_math_utils //tests:test_string_utils
      - name: Run Unit Tests
        run: |
          bazel test //tests:test_math_utils || (
            echo "=== TEST LOG START ==="
            cat /home/runner/.cache/bazel/_bazel_runner/*/execroot/_main/bazel-out/k8-fastbuild/testlogs/tests/test_math_utils/test.log || echo "Log not found"
            echo "=== TEST LOG END ==="
            exit 1
          )

      - name: Run Linter
        run: bazel test //:lint

      - name: Run Formatter Check
        run: bazel test //:format

