name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies  # Install all required packages
        run: |
          pip install --upgrade pip
          pip install pytest pylint black

      - name: Run Linter  # Runs Pylint
        run: bazel test //:lint

      - name: Run Formatter Check  # Runs Black formatting check
        run: bazel test //:format

#      - name: Run Unit Tests  # Run Python unit tests
#        run: bazel test //tests:test_math_utils //tests:test_string_utils
      - name: Run Unit Tests
        run: |
          bazel test //tests:test_math_utils || (
            echo "=== TEST LOG START ==="
            cat /home/runner/.cache/bazel/_bazel_runner/*/execroot/_main/bazel-out/k8-fastbuild/testlogs/tests/test_math_utils/test.log || echo "Log not found"
            echo "=== TEST LOG END ==="
            exit 1
          )